n1 = int(input('Um valor: '))
n2 = int(input('Outro valor:'))
print('A soma vale \n {}'.format(n1 + n2))
print('A subtração vale \n {}'.format(n1 - n2))
print('A multiplicação vale \n {}'.format(n1 * n2))
print('A divisão vale \n {}'.format(n1 / n2))